<?php

return [
    "en" => [
        "name" => "Tiếng Anh",
        "name_by_language" => "English",
        "area" => "Toàn cầu",
        "scope" => "Ngôn ngữ phổ biến toàn cầu",
        "currency" => "USD",
        "currency_code" => "$",
        "money_value" => "1",
        "decimal_places" => 2,
        "key" => "en",
        "latin"     => true,
        "flag_join_left_to_right" => false,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "phone-wallpapers",
    ],
    "zh" => [
        "name" => "Tiếng Trung",
        "name_by_language" => "中文 (Zhōngwén)",
        "area" => "Trung Quốc, Đài Loan, Singapore",
        "scope" => "Ngôn ngữ phổ biến toàn cầu",
        "currency" => "CNY",
        "currency_code" => "¥",
        "money_value" => "7",
        "decimal_places" => 2,
        "key" => "zh",
        "latin"     => false,
        "flag_join_left_to_right" => true,
        "flag_has_space_in_content" => false,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "手机壁纸",
    ],
    "es" => [
        "name" => "Tiếng Tây Ban Nha",
        "name_by_language" => "Español",
        "area" => "Tây Ban Nha, Mỹ Latinh",
        "scope" => "Ngôn ngữ phổ biến toàn cầu",
        "currency" => "EUR",
        "currency_code" => "€",
        "money_value" => "0.85",
        "decimal_places" => 2,
        "key" => "es",
        "latin"     => true,
        "flag_join_left_to_right" => false,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "fondos-de-pantalla-para-telefonos",
    ],
    "fr" => [
        "name" => "Tiếng Pháp",
        "name_by_language" => "Français",
        "area" => "Pháp, Canada, Bỉ, Thụy Sĩ, các nước châu Phi",
        "scope" => "Ngôn ngữ phổ biến toàn cầu",
        "currency" => "EUR",
        "currency_code" => "€",
        "money_value" => "0.85",
        "decimal_places" => 2,
        "key" => "fr",
        "latin"     => true,
        "flag_join_left_to_right" => false,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "fonds-d-ecran-pour-telephones",
    ],
    "vi" => [
        "name" => "Tiếng Việt",
        "name_by_language" => "Tiếng Việt",
        "area" => "Việt Nam",
        "scope" => "Ngôn ngữ khu vực châu Á",
        "currency" => "VND",
        "currency_code" => "đ",
        "money_value" => "25000",
        "decimal_places" => 0,
        "key" => "vi",
        "latin"     => true,
        "flag_join_left_to_right" => true,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "hinh-nen-dien-thoai",
    ],
];